modLoader="javafml"
loaderVersion="${loader_version}"
license="All Rights Reserved"

[[mods]]
modId="usf_admin"
version="${mod_version}"
displayName="USF Admin Systems"
authors="MeowNetStudios"
description='''
Unified admin systems for the Ultimate SMP Framework:
NPCs, Instances, Spawns, Economy, and Audit tools.
'''

[[dependencies.usf_admin]]
modId="neoforge"
type="required"
versionRange="${loader_version}"
ordering="NONE"
side="BOTH"

[[dependencies.usf_admin]]
modId="kubejs"
mandatory=false
versionRange="*"
ordering="AFTER"
side="BOTH"
