modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL=""

[[mods]]
modId="usf_adminmod"
version="${mod_version}"
displayName="USF Admin Systems"
authors="MeowNetStudios"
description='''Admin tools for the Ultimate SMP Framework.'''

[[dependencies.usf_adminmod]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.usf_adminmod]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
